# -*- coding: utf-8 -*-
"""
Free-resource map for the full CSCE graduate catalog.

Each entry: (code, title, gist, [(resource label, url), ...])
`gist` is an original one-line description of what the subject actually is —
not a reproduction of any institution's catalog text.
All linked resources are freely accessible (open courseware, author-released
books, public lecture recordings, or free-audit MOOCs) as of October 2026.
"""

CATALOG = [

# --- Foundations / bridge --------------------------------------------------
("CSCE 706", "Structured Programming in C",
 "C from first principles: memory, pointers, and the machine model under every other language.",
 [("Harvard CS50 — full course, free", "https://cs50.harvard.edu/x/"),
  ("Modern C (Jens Gustedt, free book)", "https://inria.hal.science/hal-02383654/document"),
  ("Beej's Guide to C Programming", "https://beej.us/guide/bgc/")]),

("CSCE 708", "Intro to CS Concepts and Programming (Java)",
 "Algorithmic thinking and iterative problem solving, taught through Java.",
 [("MOOC.fi Java Programming I & II (free, graded)", "https://java-programming.mooc.fi/"),
  ("Harvard CS50", "https://cs50.harvard.edu/x/"),
  ("MIT 6.0001 Intro to CS (OCW)", "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/")]),

("CSCE 709", "Intermediate Program Design with C++",
 "Object-oriented and value-semantic C++: RAII, dynamic memory without leaks, error handling.",
 [("learncpp.com — complete modern C++ course", "https://www.learncpp.com/"),
  ("cppreference", "https://en.cppreference.com/w/"),
  ("CppCon talks (free, YouTube)", "https://www.youtube.com/@CppCon")]),

("UC MATH 600", "Mathematics for Computer Science (program prerequisite)",
 "Proof technique, combinatorics, graphs, and discrete probability — the language every later course assumes.",
 [("MIT 6.1200J / 6.042J Mathematics for Computer Science (OCW, full video)", "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/"),
  ("MIT 6.1200J current lecture series", "https://www.youtube.com/watch?v=L3LMbpZIKhQ"),
  ("Lehman, Leighton & Meyer, Mathematics for CS (free book)", "https://people.csail.mit.edu/meyer/mcs.pdf")]),

("UC LINA 600", "Linear Algebra for Graphics (program prerequisite)",
 "Vectors, matrices, bases, eigen-decomposition, and projections — the entire vocabulary of the graphics pipeline.",
 [("MIT 18.06 Linear Algebra — Gilbert Strang (OCW, full video)", "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/"),
  ("3Blue1Brown, Essence of Linear Algebra (free video)", "https://www.3blue1brown.com/topics/linear-algebra"),
  ("Immersive Math — interactive linear algebra (free)", "http://immersivemath.com/ila/")]),

# --- Core systems and theory ----------------------------------------------
("CSCE 603", "Database Systems and Applications",
 "Codd's relational model and hands-on schema design for non-majors.",
 [("Stanford Databases MOOC (Jennifer Widom, free)", "https://online.stanford.edu/courses/soe-ydatabases-databases"),
  ("CMU 15-445 Intro to Database Systems (free videos)", "https://15445.courses.cs.cmu.edu/"),
  ("Stanford CS145 Introduction to Databases (archived)", "https://web.archive.org/web/2017/http://web.stanford.edu/class/cs145/"),
  ("PostgreSQL Tutorial", "https://www.postgresqltutorial.com/")]),

("CSCE 608", "Database Systems",
 "How a DBMS is actually built: storage, indexing, query optimization, concurrency, recovery.",
 [("CMU 15-445/645 — Andy Pavlo, full lectures free", "https://15445.courses.cs.cmu.edu/"),
  ("CMU 15-721 Advanced Database Systems", "https://15721.courses.cs.cmu.edu/"),
  ("MIT 6.5830 Database Systems, Fall 2023 (OCW)", "https://dsg.csail.mit.edu/6.5830/"),
  ("Database Internals / readings list", "https://www.redbook.io/")]),

("CSCE 605", "Compiler Design",
 "Beyond parsing: dataflow analysis, SSA, register allocation, and optimization passes.",
 [("Stanford CS143 Compilers (free, edX/self-paced)", "https://web.stanford.edu/class/cs143/"),
  ("Crafting Interpreters (Bob Nystrom, free book)", "https://craftinginterpreters.com/"),
  ("Neso Academy, Compiler Design (free video series)", "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjT3oJxFXRgjPNzeS-LFY-q"),
  ("LLVM Kaleidoscope tutorial", "https://llvm.org/docs/tutorial/")]),

("CSCE 606", "Software Engineering",
 "Building software that survives other people: process, design, testing, maintainability.",
 [("Berkeley CS169 — Engineering Software as a Service (edX, free audit)", "https://www.edx.org/learn/software-engineering/university-of-california-berkeley-agile-development-using-ruby-on-rails-the-basics"),
  ("MIT 6.031 Software Construction (open)", "https://web.mit.edu/6.031/www/"),
  ("Software Engineering at Google (free online)", "https://abseil.io/resources/swe-book")]),

("CSCE 611", "Operating Systems",
 "Scheduling, virtual memory, concurrency, and I/O — by building a kernel, not reading about one.",
 [("MIT 6.1810 Operating System Engineering (xv6, free)", "https://pdos.csail.mit.edu/6.1810/"),
  ("OSTEP — Operating Systems: Three Easy Pieces (free book)", "https://pages.cs.wisc.edu/~remzi/OSTEP/"),
  ("MIT 6.S081 Operating System Engineering, 2020 (lecture video + labs)", "https://pdos.csail.mit.edu/6.S081/2020/schedule.html"),
  ("Berkeley CS162 (free lectures)", "https://cs162.org/")]),

("CSCE 612", "Applied Networks and Distributed Processing",
 "The layered stack as engineering practice: build a working TCP, then reason about real protocols.",
 [("Stanford CS144 — Computer Networking (free, build your own TCP)", "https://cs144.github.io/"),
  ("Kurose & Ross companion site", "https://gaia.cs.umass.edu/kurose_ross/"),
  ("Beej's Guide to Network Programming", "https://beej.us/guide/bgnet/")]),

("CSCE 614", "Computer Architecture",
 "Pipelines, caches, memory hierarchy, multicore, and why your code is slow.",
 [("ETH Zurich — Onur Mutlu, Computer Architecture (full lectures)", "https://safari.ethz.ch/architecture/"),
  ("Nand2Tetris — build a computer from NAND gates", "https://www.nand2tetris.org/"),
  ("MIT 6.004 Computation Structures (OCW, Spring 2017)", "https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/"),
  ("MITx 6.004.1x Computation Structures: Digital Circuits (edX)", "https://www.edx.org/learn/computer-programming/massachusetts-institute-of-technology-computation-structures-1-digital-circuits"),
  ("Berkeley CS152/CS252", "https://inst.eecs.berkeley.edu/~cs152/")]),

("CSCE 616", "Intro to Hardware Design Verification",
 "Proving a chip does what the spec says: testbenches, coverage, assertions.",
 [("ChipVerify — SystemVerilog & UVM tutorials (free)", "https://www.chipverify.com/"),
  ("Verilator (open-source simulator) docs", "https://verilator.org/guide/latest/"),
  ("Verification Academy (free account)", "https://verificationacademy.com/")]),

("CSCE 714", "Advanced Hardware Design Functional Verification",
 "UVM at scale: reusable verification IP, constrained-random stimulus, coverage closure.",
 [("ChipVerify UVM tutorial", "https://www.chipverify.com/uvm/uvm-tutorial"),
  ("Accellera UVM standard (free)", "https://www.accellera.org/downloads/standards/uvm"),
  ("cocotb — Python verification (free)", "https://www.cocotb.org/")]),

("CSCE 620", "Computational Geometry",
 "Convex hulls, Voronoi diagrams, triangulation, range search — the geometry under collision and meshing.",
 [("David Mount, CMSC 754 lecture notes (free PDF)", "https://www.cs.umd.edu/class/spring2020/cmsc754/Lects/cmsc754-spring2020-lects.pdf"),
  ("CGAL — the reference implementation", "https://www.cgal.org/"),
  ("Computational Geometry (TU Eindhoven course page)", "https://www.win.tue.nl/~kbuchin/teaching/")]),

("CSCE 624", "Sketch Recognition",
 "Turning freehand strokes into meaning: feature-, geometry-, and timing-based recognizers.",
 [("$1 / $N / $P stroke recognizer family (free code + papers)", "https://depts.washington.edu/acelab/proj/dollar/"),
  ("Berkeley CS188 (classification foundations)", "https://inst.eecs.berkeley.edu/~cs188/"),
  ("Sketch-a-Net / QuickDraw dataset", "https://quickdraw.withgoogle.com/data")]),

("CSCE 625", "Artificial Intelligence",
 "Search, constraint satisfaction, adversarial games, logic, planning, probabilistic reasoning.",
 [("Berkeley CS188 — Intro to AI (free, with Pacman projects)", "https://inst.eecs.berkeley.edu/~cs188/"),
  ("AIMA book companion site", "https://aima.cs.berkeley.edu/"),
  ("MIT 6.034 — Patrick Winston lectures (OCW)", "https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/"),
  ("Harvard CS50's Introduction to AI with Python (free)", "https://cs50.harvard.edu/ai/")]),

("CSCE 626", "Parallel Algorithm Design and Analysis",
 "Work-span analysis, parallel lower bounds, and algorithms built for wide machines.",
 [("CMU 15-210 Parallel and Sequential Data Structures (free notes)", "http://www.cs.cmu.edu/~15210/"),
  ("Blelloch, Prefix Sums and Their Applications (free)", "https://www.cs.cmu.edu/~guyb/papers/Ble93.pdf"),
  ("CMU 15-418 Parallel Computer Architecture", "http://www.cs.cmu.edu/~418/")]),

("CSCE 627", "Theory of Computability",
 "Automata, Turing machines, decidability, and the hard edge of what computers cannot do.",
 [("MIT 18.404J Theory of Computation — Sipser, full video (OCW)", "https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/"),
  ("Stanford CS103 handouts (free)", "https://web.stanford.edu/class/cs103/"),
  ("Jeff Erickson, Models of Computation (free book)", "https://jeffe.cs.illinois.edu/teaching/algorithms/")]),

("CSCE 637", "Complexity Theory",
 "P, NP, space, randomness, alternation, and the relationships between complexity classes.",
 [("Arora & Barak, Computational Complexity (free draft)", "https://theory.cs.princeton.edu/complexity/book.pdf"),
  ("CMU 15-455 Undergraduate Complexity — Ryan O'Donnell (free video)", "https://www.youtube.com/playlist?list=PLm3J0oaFux3b8Gg1DdaJOzYNsaXYLAOKH"),
  ("Computational Complexity Blog", "https://blog.computationalcomplexity.org/")]),

("CSCE 628", "Computational Biology",
 "Genomics and proteomics restated as string, graph, and optimization problems.",
 [("MIT 6.047 Computational Biology — Kellis (OCW + video)", "https://ocw.mit.edu/courses/6-047-computational-biology-fall-2015/"),
  ("Rosalind — bioinformatics problem set (free)", "https://rosalind.info/"),
  ("UCSD Bioinformatics Specialization (free audit)", "https://www.coursera.org/specializations/bioinformatics")]),

("CSCE 629", "Analysis of Algorithms",
 "Design techniques, rigorous analysis, NP-completeness, approximation and randomization.",
 [("MIT 6.046J Design and Analysis of Algorithms (OCW, full video)", "https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/"),
  ("Jeff Erickson, Algorithms (free book + exercises)", "https://jeffe.cs.illinois.edu/teaching/algorithms/"),
  ("MIT 6.006 Introduction to Algorithms, Spring 2020 (OCW, full video)", "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/"),
  ("Tim Roughgarden, Algorithms Illuminated (free lectures)", "https://www.algorithmsilluminated.org/")]),

("CSCE 658", "Randomized Algorithms",
 "Probabilistic method, concentration bounds, and algorithms that are fast because they gamble.",
 [("Jeff Erickson, randomization chapters (free)", "https://jeffe.cs.illinois.edu/teaching/algorithms/"),
  ("Harvard CS 225 Sketching Algorithms — Jelani Nelson (free video+notes)", "https://www.sketchingbigdata.org/"),
  ("Mitzenmacher & Upfal lecture slides (free)", "https://www.cs.cmu.edu/~avrim/Randalgs97/")]),

("CSCE 669", "Computational Optimization",
 "Polyhedral combinatorics, LP/IP duality, and the geometry behind approximation guarantees.",
 [("Boyd & Vandenberghe, Convex Optimization (free book + EE364A video)", "https://web.stanford.edu/~boyd/cvxbook/"),
  ("MIT 15.093 Optimization Methods (OCW)", "https://ocw.mit.edu/courses/15-093j-optimization-methods-fall-2009/"),
  ("Stanford EE364A lecture videos", "https://www.youtube.com/playlist?list=PL3940DD956CDF0622")]),

("CSCE 717", "Algorithmic Game Theory",
 "Equilibria, mechanism design, auctions, and the price of letting agents act selfishly.",
 [("Tim Roughgarden, CS364A — Twenty Lectures on AGT (free notes + video)", "https://timroughgarden.org/f13/f13.html"),
  ("Algorithmic Game Theory (Nisan et al., free PDF)", "https://www.cs.cmu.edu/~sandholm/cs15-892F13/algorithmic-game-theory.pdf"),
  ("Shoham & Leyton-Brown, Multiagent Systems (free)", "http://www.masfoundations.org/")]),

("CSCE 640", "Quantum Algorithms",
 "The circuit model, Deutsch–Jozsa through Shor and Grover, and what quantum speedup really means.",
 [("IBM Quantum Learning — full free curriculum", "https://learning.quantum.ibm.com/"),
  ("John Watrous, Quantum Information lectures (free)", "https://johnwatrous.com/lecture-notes/"),
  ("Berkeley CS191 / edX Quantum Mechanics & Quantum Computation", "https://inst.eecs.berkeley.edu/~cs191/")]),

# --- AI / ML ---------------------------------------------------------------
("CSCE 633", "Machine Learning",
 "Supervised and unsupervised learning from the ground up: bias/variance, kernels, ensembles.",
 [("Stanford CS229 — full lectures + notes (free)", "https://cs229.stanford.edu/"),
  ("An Introduction to Statistical Learning (free PDF)", "https://www.statlearning.com/"),
  ("The Elements of Statistical Learning (free PDF)", "https://hastie.su.domains/ElemStatLearn/")]),

("CSCE 636", "Deep Learning",
 "Neural architectures, optimization, regularization, and modern representation learning.",
 [("Karpathy, Neural Networks: Zero to Hero (free)", "https://karpathy.ai/zero-to-hero.html"),
  ("Dive into Deep Learning (free interactive book)", "https://d2l.ai/"),
  ("Stanford CS231n — CNNs for Visual Recognition", "https://cs231n.github.io/"),
  ("MIT 6.S191 Introduction to Deep Learning (free, annual)", "https://introtodeeplearning.com/"),
  ("fast.ai Practical Deep Learning", "https://course.fast.ai/")]),

("CSCE 642", "Deep Reinforcement Learning",
 "MDPs, policy gradients, Q-learning, actor-critic, and model-based RL.",
 [("Berkeley CS285 Deep RL — full lectures (free)", "https://rail.eecs.berkeley.edu/deeprlcourse/"),
  ("Sutton & Barto, Reinforcement Learning (free book)", "http://incompleteideas.net/book/the-book.html"),
  ("OpenAI Spinning Up in Deep RL", "https://spinningup.openai.com/"),
  ("David Silver, DeepMind RL course (free video)", "https://www.davidsilver.uk/teaching/")]),

("CSCE 638", "Natural Language Processing",
 "Language models, syntax, semantics, and the application stack from IE to dialogue.",
 [("Stanford CS224N — NLP with Deep Learning (free video)", "https://web.stanford.edu/class/cs224n/"),
  ("Jurafsky & Martin, Speech and Language Processing (free draft)", "https://web.stanford.edu/~jurafsky/slp3/"),
  ("Hugging Face NLP Course (free)", "https://huggingface.co/learn/nlp-course")]),

("CSCE 630", "Speech Processing",
 "Acoustics, feature extraction, recognition, synthesis, and voice modification.",
 [("Jurafsky & Martin SLP3 — speech chapters (free)", "https://web.stanford.edu/~jurafsky/slp3/"),
  ("ESPnet end-to-end speech toolkit + tutorials", "https://espnet.github.io/espnet/"),
  ("Kaldi documentation", "https://kaldi-asr.org/doc/")]),

("CSCE 666", "Pattern Analysis",
 "Density estimation, dimensionality reduction, clustering, Bayesian and geometric classifiers.",
 [("Bishop, Pattern Recognition and Machine Learning (free PDF)", "https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/"),
  ("The Elements of Statistical Learning (free PDF)", "https://hastie.su.domains/ElemStatLearn/"),
  ("scikit-learn user guide", "https://scikit-learn.org/stable/user_guide.html")]),

("CSCE 676", "Data Mining and Analysis",
 "Pattern mining, clustering, classification, and analysis at dataset scale.",
 [("Mining of Massive Datasets — free book + Stanford CS246 video", "http://www.mmds.org/"),
  ("Zaki & Meira, Data Mining and Machine Learning (free PDF)", "https://dataminingbook.info/"),
  ("Stanford CS246", "http://web.stanford.edu/class/cs246/")]),

("CSCE 727", "Algorithmic Foundations of Big Data Computing",
 "Streaming, sketching, sublinear-time and sublinear-space algorithms.",
 [("Sketching Algorithms — Jelani Nelson (free video + notes)", "https://www.sketchingbigdata.org/"),
  ("Mining of Massive Datasets", "http://www.mmds.org/"),
  ("Data Streams: Algorithms and Applications (Muthukrishnan, free)", "https://www.cs.rutgers.edu/~muthu/stream-1-1.ps")]),

("CSCE 726", "Large-Scale Optimization for Machine Learning",
 "SGD and its descendants: momentum, adaptivity, variance reduction, convergence proofs.",
 [("Bubeck, Convex Optimization: Algorithms and Complexity (free)", "https://arxiv.org/abs/1405.4980"),
  ("Boyd, Convex Optimization + EE364B", "https://web.stanford.edu/~boyd/cvxbook/"),
  ("Optimization for Machine Learning (Hazan, free lecture notes)", "https://arxiv.org/abs/1909.03550")]),

("CSCE 631", "Intelligent Agents",
 "Agent architectures, coordination, negotiation, and multi-agent equilibria.",
 [("Shoham & Leyton-Brown, Multiagent Systems (free book)", "http://www.masfoundations.org/"),
  ("Berkeley CS188 — multi-agent search", "https://inst.eecs.berkeley.edu/~cs188/"),
  ("Roughgarden CS364A (mechanism design)", "https://timroughgarden.org/f13/f13.html")]),

("CSCE 635", "AI Robotics",
 "Perception-action loops for mobile robots, grounded in biology and cognition rather than control theory.",
 [("Modern Robotics — free book, video, Coursera", "https://modernrobotics.northwestern.edu/"),
  ("Peter Corke, Robot Academy (free video)", "https://robotacademy.net.au/"),
  ("UC Berkeley CS287 Advanced Robotics — Pieter Abbeel (free)", "https://people.eecs.berkeley.edu/~pabbeel/cs287-fa19/"),
  ("ROS 2 tutorials", "https://docs.ros.org/en/rolling/Tutorials.html")]),

("CSCE 752", "Robotics and Spatial Intelligence",
 "Frames, kinematics, motion planning, calibration, SLAM, and navigation.",
 [("Modern Robotics (Lynch & Park) — free book + lectures", "https://modernrobotics.northwestern.edu/"),
  ("LaValle, Planning Algorithms (free book)", "http://lavalle.pl/planning/"),
  ("Cyrill Stachniss, Mobile Sensing & Robotics (free video)", "https://www.ipb.uni-bonn.de/sensing-and-robotics-2021/")]),

("CSCE 753", "Computer Vision and Robot Perception",
 "Projective geometry, multi-view reconstruction, features, lidar, and SLAM.",
 [("Szeliski, Computer Vision: Algorithms and Applications (free book)", "https://szeliski.org/Book/"),
  ("First Principles of Computer Vision — Shree Nayar (free video)", "https://fpcv.cs.columbia.edu/"),
  ("Stachniss SLAM course (free video)", "https://www.ipb.uni-bonn.de/msr2-2020/")]),

("CSCE 634", "Intelligent User Interfaces",
 "Interfaces that model and adapt to their user, task, and context.",
 [("Scott Klemmer, HCI (free audit)", "https://www.coursera.org/learn/human-computer-interaction"),
  ("Nielsen Norman Group articles (free)", "https://www.nngroup.com/articles/"),
  ("Stanford CS 347 / HCI reading lists", "https://hci.stanford.edu/courses/")]),

# --- Graphics, geometry, simulation, imaging -------------------------------
("CSCE 641", "Computer Graphics",
 "The full pipeline: transforms, rasterization, shading, visibility, texturing, animation.",
 [("GAMES101 — Lingqi Yan, Modern Computer Graphics (free, English slides)", "https://sites.cs.ucsb.edu/~lingqi/teaching/games101.html"),
  ("CMU 15-462/662 — Keenan Crane (free video)", "https://15462.courses.cs.cmu.edu/"),
  ("Cem Yuksel, Interactive Computer Graphics (Utah, free video)", "https://graphics.cs.utah.edu/courses/cs6610/"),
  ("UC San Diego CSE167x Computer Graphics (edX, free audit)", "https://www.edx.org/learn/computer-graphics/the-university-of-california-san-diego-computer-graphics"),
  ("Scratchapixel — from-scratch graphics", "https://www.scratchapixel.com/")]),

("CSCE 645", "Geometric Modeling",
 "Curves, surfaces, solids: Bezier and spline theory, topology, Boolean operations, mesh processing.",
 [("Keenan Crane, Discrete Differential Geometry (free notes + video + code)", "https://brickisland.net/ddg-web/"),
  ("libigl geometry processing tutorial (free)", "https://libigl.github.io/tutorial/"),
  ("MIT 6.8410 Shape Analysis — Justin Solomon", "https://groups.csail.mit.edu/gdpgroup/6838_spring_2021.html")]),

("CSCE 647", "Image Synthesis",
 "Light transport from first principles: the rendering equation, Monte Carlo, importance sampling.",
 [("Physically Based Rendering, 4th ed. — free online book", "https://pbr-book.org/"),
  ("Ray Tracing in One Weekend series (free)", "https://raytracing.github.io/"),
  ("TU Wien Rendering / Light Transport course (free video)", "https://www.youtube.com/playlist?list=PLujxSBD-JXgnGmsn7gEyN28P1DnRZG7qi")]),

("CSCE 646", "Digital Image",
 "2D image representation, filtering, warping, color spaces, and enhancement.",
 [("Rich Radke, Digital Image Processing (RPI, free video)", "https://www.youtube.com/playlist?list=PLuh62Q4Sv7BUf60vkjePfcOQc8sHxmnDX"),
  ("OpenCV tutorials", "https://docs.opencv.org/4.x/d9/df8/tutorial_root.html"),
  ("scikit-image user guide", "https://scikit-image.org/docs/stable/user_guide.html")]),

("CSCE 648", "Computer Aided Sculpting",
 "Form, proportion, and gesture expressed through parametric and implicit surfaces.",
 [("Blender Fundamentals + sculpting (free, official)", "https://www.blender.org/support/tutorials/"),
  ("Keenan Crane, Discrete Differential Geometry", "https://brickisland.net/ddg-web/"),
  ("Inigo Quilez — SDF and implicit modeling articles (free)", "https://iquilezles.org/articles/")]),

("CSCE 649", "Physically-Based Modeling",
 "Particles, rigid bodies, deformables, constraints, and fluids for animation.",
 [("Baraff & Witkin, Physically Based Modeling (Pixar course notes, free)", "https://graphics.pixar.com/tutorials/"),
  ("Ten Minute Physics — Matthias Muller (free video + code)", "https://matthias-research.github.io/pages/tenMinutePhysics/"),
  ("Bridson, Fluid Simulation for Computer Graphics (course notes, free)", "https://www.cs.ubc.ca/~rbridson/fluidsimulation/")]),

("CSCE 650", "Virtual Reality",
 "Perception, tracking, stereo rendering, latency, and the design of immersive experience.",
 [("LaValle, Virtual Reality (free book + Illinois lectures)", "http://lavalle.pl/vr/"),
  ("Stanford EE267 — build your own HMD (free materials)", "https://web.stanford.edu/class/ee267/"),
  ("Unreal/Unity XR documentation", "https://dev.epicgames.com/documentation/en-us/unreal-engine/xr-development")]),

("CSCE 748", "Computational Photography",
 "Imaging pipelines, HDR, lightfields, coded apertures, and computational light transport.",
 [("CMU 15-463 Computational Photography — Gkioulekas (free)", "http://graphics.cs.cmu.edu/courses/15-463/"),
  ("Marc Levoy, Lectures on Digital Photography (free)", "https://sites.google.com/site/marclevoylectures/"),
  ("Georgia Tech CS6475 Computational Photography (free)", "https://www.udacity.com/course/computational-photography--ud955")]),

("CSCE 679", "Data Visualization",
 "Visual encoding, perception, interaction, and narrative structure for data.",
 [("Wilke, Fundamentals of Data Visualization (free book)", "https://clauswilke.com/dataviz/"),
  ("UW CSE 512 Data Visualization — Jeffrey Heer (free)", "https://courses.cs.washington.edu/courses/cse512/"),
  ("D3 / Observable Plot documentation", "https://observablehq.com/plot/")]),

("CSCE 743", "Digital Fabrication Studio",
 "Machines, materials, and programmable matter as a computational design medium.",
 [("MIT MAS.863 How to Make (Almost) Anything (free archive)", "https://fab.cba.mit.edu/classes/863.23/"),
  ("Fab Academy course archive", "https://fabacademy.org/"),
  ("Prusa / open 3D printing knowledge base", "https://help.prusa3d.com/")]),

("CSCE 653", "Computer Methods in Applied Sciences",
 "Numerical analysis for engineers: roots, interpolation, quadrature, linear systems, ODEs/PDEs.",
 [("MIT 18.330 Introduction to Numerical Analysis (OCW)", "https://ocw.mit.edu/courses/18-330-introduction-to-numerical-analysis-spring-2012/"),
  ("MIT 18.335 Numerical Methods — Steven Johnson (free notes)", "https://github.com/mitmath/18335"),
  ("Numerical Recipes / SciPy lecture notes (free)", "https://scipy-lectures.org/")]),

# --- Parallel, distributed, HPC -------------------------------------------
("CSCE 735", "Parallel Computing",
 "Multicore, SIMD, GPU, and distributed-memory programming with a performance mindset.",
 [("CMU 15-418 Parallel Computer Architecture & Programming (free)", "http://www.cs.cmu.edu/~418/"),
  ("Stanford CS149 (free slides + assignments)", "https://gfxcourses.stanford.edu/cs149/"),
  ("NVIDIA CUDA C++ Programming Guide", "https://web.archive.org/web/20260911074013/https://docs.nvidia.com/cuda/cuda-c-programming-guide/"),
  ("OLCF CUDA Training Series (free video)", "https://www.olcf.ornl.gov/cuda-training-series/")]),

("CSCE 654", "Supercomputing",
 "Vectorization, numerical kernels, scaling studies, and performance measurement at HPC scale.",
 [("HPC Carpentry (free lessons)", "https://www.hpc-carpentry.org/"),
  ("Argonne / ALCF training archive (free video)", "https://www.alcf.anl.gov/support-center/training"),
  ("CMU 15-418", "http://www.cs.cmu.edu/~418/")]),

("CSCE 662", "Distributed Processing Systems",
 "RPC, replication, consistency, fault tolerance, and distributed storage.",
 [("MIT 6.5840 Distributed Systems (free video + labs)", "https://pdos.csail.mit.edu/6.824/"),
  ("van Steen & Tanenbaum, Distributed Systems (free book)", "https://www.distributed-systems.net/index.php/books/ds4/"),
  ("Google SRE Book (free)", "https://sre.google/books/")]),

("CSCE 668", "Distributed Algorithms and Systems",
 "Leader election, mutual exclusion, consensus, logical time, snapshots, fault tolerance.",
 [("Suomela, Distributed Algorithms (free book)", "https://jukkasuomela.fi/da/"),
  ("MIT 6.852 Distributed Algorithms (OCW)", "https://ocw.mit.edu/courses/6-852j-distributed-algorithms-fall-2009/"),
  ("Raft / Paxos made live (free papers)", "https://raft.github.io/")]),

("CSCE 678", "Distributed Systems and Cloud Computing",
 "MapReduce, coordination, replication, elasticity, and the economics of the cloud.",
 [("Cloud Computing Concepts — Indranil Gupta (free audit)", "https://www.coursera.org/learn/cloud-computing"),
  ("MIT 6.5840", "https://pdos.csail.mit.edu/6.824/"),
  ("Google SRE Workbook (free)", "https://sre.google/workbook/table-of-contents/")]),

("CSCE 664", "Wireless and Mobile Systems",
 "PHY/MAC fundamentals, scheduling, mobile transport, ad-hoc and sensor networks.",
 [("Stanford CS144 (networking base)", "https://cs144.github.io/"),
  ("NPTEL Wireless Communication (free video)", "https://nptel.ac.in/courses/117104099"),
  ("MIT 6.02 Intro to EECS II — digital communication (OCW)", "https://ocw.mit.edu/courses/6-02-introduction-to-eecs-ii-digital-communication-systems-fall-2012/")]),

("CSCE 670", "Information Storage and Retrieval",
 "Indexing, compression, ranking, and evaluation for very large document collections.",
 [("Manning, Introduction to Information Retrieval (free book)", "https://nlp.stanford.edu/IR-book/"),
  ("Search Engines: Information Retrieval in Practice (free PDF)", "https://ciir.cs.umass.edu/irbook/"),
  ("Stanford CS276", "https://web.stanford.edu/class/cs276/")]),

# --- HCI / media -----------------------------------------------------------
("CSCE 655", "Human-Centered Computing",
 "Interaction concepts, prototyping, evaluation, visual design, and information structure.",
 [("Klemmer, Human-Computer Interaction (free audit)", "https://www.coursera.org/learn/human-computer-interaction"),
  ("Nielsen Norman Group (free articles)", "https://www.nngroup.com/articles/"),
  ("Stanford d.school resources (free)", "https://dschool.stanford.edu/resources")]),

("CSCE 671", "Computer-Human Interaction",
 "History, theory, task analysis, user modeling, and interaction styles.",
 [("Klemmer, HCI (free audit)", "https://www.coursera.org/learn/human-computer-interaction"),
  ("Interaction Design Foundation open literature", "https://www.interaction-design.org/literature"),
  ("ACM CHI proceedings (open access portion)", "https://dl.acm.org/conference/chi")]),

("CSCE 672", "Computer Supported Collaborative Work",
 "Technical systems for cooperative work, and their social and organizational consequences.",
 [("ACM CSCW proceedings", "https://dl.acm.org/conference/cscw"),
  ("Klemmer HCI (foundation)", "https://www.coursera.org/learn/human-computer-interaction"),
  ("MIT OCW — Collective Intelligence", "https://ocw.mit.edu/courses/15-359-collective-intelligence-spring-2019/")]),

("CSCE 632", "Accessible Computing",
 "Disability, universal design, accessibility standards, and inclusive software practice.",
 [("W3C Web Accessibility Initiative tutorials (free)", "https://www.w3.org/WAI/tutorials/"),
  ("WCAG 2.2 standard + Understanding docs (free)", "https://www.w3.org/WAI/WCAG22/quickref/"),
  ("Teach Access materials (free)", "https://teachaccess.org/resources/")]),

("CSCE 656", "Computers and New Media",
 "Computation as an authoring medium, and the author/reader relationship it creates.",
 [("Lev Manovich, free books and essays", "http://manovich.net/"),
  ("MIT OCW — Comparative Media Studies", "https://ocw.mit.edu/search/?d=Comparative%20Media%20Studies"),
  ("Electronic Literature Collection (free)", "https://collection.eliterature.org/")]),

# --- Security and cryptography --------------------------------------------
("CSCE 701", "Foundations of Cybersecurity",
 "Crypto primitives, authentication, system and network defense, and the threat model habit.",
 [("MIT 6.858 Computer Systems Security (OCW, free video)", "https://ocw.mit.edu/courses/6-858-computer-systems-security-fall-2014/"),
  ("Stanford CS155 Computer and Network Security (free)", "https://cs155.stanford.edu/"),
  ("RIT Cybersecurity Fundamentals (edX, free audit)", "https://www.edx.org/learn/cybersecurity/rochester-institute-of-technology-cybersecurity-fundamentals"),
  ("SEED Labs — free hands-on security labs", "https://seedsecuritylabs.org/")]),

("CSCE 711", "Foundation of Modern Cryptography",
 "Provable security: PRGs/PRFs, block ciphers, MACs, public key, signatures, zero knowledge.",
 [("Boneh & Shoup, A Graduate Course in Applied Cryptography (free)", "https://toc.cryptobook.us/"),
  ("Dan Boneh, Cryptography I (free audit)", "https://www.coursera.org/learn/crypto"),
  ("Cryptopals challenges (free)", "https://cryptopals.com/")]),

("CSCE 749", "Applied Cryptography",
 "MPC, verifiable computation, and zero-knowledge proofs applied to ML and blockchains.",
 [("ZKP MOOC — Berkeley/Stanford (free video)", "https://zk-learning.org/"),
  ("Evans, Kolesnikov & Rosulek, Pragmatic MPC (free book)", "https://securecomputation.org/"),
  ("Boneh & Shoup (free)", "https://toc.cryptobook.us/")]),

("CSCE 713", "Software Security",
 "Secure design, code review, static and dynamic analysis, fuzzing, and security testing.",
 [("OWASP Top 10 + Cheat Sheet Series (free)", "https://cheatsheetseries.owasp.org/"),
  ("pwn.college — free hands-on exploitation curriculum", "https://pwn.college/"),
  ("MIT 6.858 (free video)", "https://ocw.mit.edu/courses/6-858-computer-systems-security-fall-2014/")]),

("CSCE 652", "Software Reverse Engineering",
 "Binary formats, disassembly, control-flow recovery, static/dynamic analysis, obfuscation.",
 [("OpenSecurityTraining2 — free RE courses", "https://ost2.fyi/"),
  ("Ghidra (NSA) + official course materials (free)", "https://github.com/NationalSecurityAgency/ghidra"),
  ("LiveOverflow, Binary Exploitation (free video)", "https://www.youtube.com/@LiveOverflow")]),

("CSCE 712", "Digital Forensic Engineering",
 "Acquisition, preservation, analysis, and the legal constraints on digital evidence.",
 [("Autopsy / The Sleuth Kit documentation (free)", "https://www.autopsy.com/support/"),
  ("OpenSecurityTraining2 forensics tracks", "https://ost2.fyi/"),
  ("NIST Computer Forensics Tool Testing (free)", "https://www.nist.gov/itl/ssd/software-quality-group/computer-forensics-tool-testing-program-cftt")]),

("CSCE 715", "Secure Authentication Systems",
 "Passwords, MFA, biometrics, end-to-end protocols, and authentication side channels.",
 [("NIST SP 800-63 Digital Identity Guidelines (free)", "https://pages.nist.gov/800-63-3/"),
  ("WebAuthn Guide (free)", "https://webauthn.guide/"),
  ("FIDO Alliance specifications (free)", "https://fidoalliance.org/specifications/")]),

("CSCE 716", "Foundations and Applications of Blockchains",
 "Consensus and trust assumptions, smart contracts, and what blockchains actually buy you.",
 [("Princeton, Bitcoin and Cryptocurrency Technologies (free book + video)", "https://bitcoinbook.cs.princeton.edu/"),
  ("MIT 15.S12 Blockchain and Money — Gensler (OCW)", "https://ocw.mit.edu/courses/15-s12-blockchain-and-money-fall-2018/"),
  ("Ethereum developer documentation (free)", "https://ethereum.org/en/developers/docs/")]),

("CSCE 765", "Network Security",
 "Protocol vulnerabilities layer by layer, and the defenses that actually hold.",
 [("Stanford CS155 (free)", "https://cs155.stanford.edu/"),
  ("SEED Labs network security labs (free)", "https://seedsecuritylabs.org/Labs_20.04/Networking/"),
  ("Practical Networking — TLS/crypto series (free video)", "https://www.practicalnetworking.net/")]),

("CSCE 665", "Advanced Networking and Security",
 "Offensive and defensive tooling against live networks and protocols.",
 [("pwn.college (free)", "https://pwn.college/"),
  ("SEED Labs (free)", "https://seedsecuritylabs.org/"),
  ("Wireshark documentation + sample captures (free)", "https://www.wireshark.org/docs/")]),

("CSCE 702", "Law and Policy in Cybersecurity",
 "Governance, oversight, procurement, and the regulatory landscape across jurisdictions.",
 [("NIST Cybersecurity Framework 2.0 (free)", "https://www.nist.gov/cyberframework"),
  ("CISA free resources and guidance", "https://www.cisa.gov/resources-tools/resources"),
  ("Berkman Klein Center publications (free)", "https://cyber.harvard.edu/publications")]),

("CSCE 703", "Cybersecurity Risk",
 "Risk identification, assessment, treatment, and audit frameworks.",
 [("NIST SP 800-30 Risk Assessment (free)", "https://csrc.nist.gov/pubs/sp/800/30/r1/final"),
  ("NIST SP 800-37 Risk Management Framework (free)", "https://csrc.nist.gov/pubs/sp/800/37/r2/final"),
  ("FAIR risk quantification introduction (free)", "https://www.fairinstitute.org/what-is-fair")]),

("CSCE 704", "Data Analytics for Cybersecurity",
 "Clustering, supervised learning, anomaly detection, and visualization applied to attacks.",
 [("MITRE ATT&amp;CK (free)", "https://attack.mitre.org/"),
  ("Stanford CS229 (ML foundation)", "https://cs229.stanford.edu/"),
  ("Elastic Security / detection-rules (free, open)", "https://github.com/elastic/detection-rules")]),

("CSCE 680", "Testing and Diagnosis of Digital Systems",
 "Fault models, ATPG, scan chains, BIST, and design for testability.",
 [("NPTEL VLSI Testing (free video)", "https://nptel.ac.in/courses/117106092"),
  ("Vishwani Agrawal, VLSI Testing lectures (free)", "https://www.eng.auburn.edu/~agrawvd/COURSE/E7250_05/course.html"),
  ("OpenLane / open EDA documentation", "https://openlane.readthedocs.io/")]),

# --- Non-coursework requirements ------------------------------------------
("CSCE 681", "Seminar",
 "Structured exposure to current research: read, present, and defend recent papers.",
 [("SIGGRAPH / SIGGRAPH Asia open-access papers", "https://dl.acm.org/conference/siggraph"),
  ("arXiv cs.GR daily feed", "https://arxiv.org/list/cs.GR/recent"),
  ("Two Minute Papers (free video)", "https://www.youtube.com/@TwoMinutePapers")]),

("CSCE 643", "Seminar in Intelligent Systems and Robotics",
 "Reading-group format tracking current robotics and intelligent-systems research.",
 [("CoRL / ICRA / RSS open-access proceedings", "https://www.roboticsproceedings.org/"),
  ("arXiv cs.RO recent", "https://arxiv.org/list/cs.RO/recent"),
  ("Robot Brains / robotics seminar recordings", "https://www.therobotbrains.ai/")]),

("CSCE 689", "Special Topics",
 "Instructor-chosen advanced topic; in this program, a self-designed deep dive.",
 [("Open Syllabus — find a syllabus on any topic", "https://opensyllabus.org/"),
  ("MIT OpenCourseWare full catalog", "https://ocw.mit.edu/"),
  ("Awesome-* curated topic lists on GitHub", "https://github.com/topics/awesome")]),

("CSCE 684", "Professional Internship",
 "Supervised practice in a professional setting.",
 [("Open-source contribution as substitute practice", "https://github.com/explore"),
  ("Google Summer of Code", "https://summerofcode.withgoogle.com/"),
  ("Outreachy", "https://www.outreachy.org/")]),

("CSCE 685", "Directed Studies",
 "A small, scoped research problem chosen to build technique.",
 [("The Craft of Research (method, library access)", "https://press.uchicago.edu/"),
  ("How to Read a Paper — S. Keshav (free)", "https://web.stanford.edu/class/ee384m/Handouts/HowtoReadPaper.pdf"),
  ("Papers With Code", "https://paperswithcode.com/")]),

("CSCE 691", "Research",
 "Sustained independent research toward a thesis.",
 [("The Researcher's Bible (free)", "https://www.inf.ed.ac.uk/teaching/courses/irm/notes/bible.html"),
  ("How to Write a Great Research Paper — S. Peyton Jones (free)", "https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/"),
  ("arXiv + Zotero workflow", "https://www.zotero.org/")]),

("CSCE 682", "Introduction to Doctoral Studies",
 "Orientation to doctoral milestones, publication, and presentation of work.",
 [("PhD Grind — Philip Guo (free book)", "https://pgbovine.net/PhD-memoir.htm"),
  ("How to Write a Great Research Paper (free)", "https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/"),
  ("The Researcher's Bible (free)", "https://www.inf.ed.ac.uk/teaching/courses/irm/notes/bible.html")]),
]
