# -*- coding: utf-8 -*-
"""University of Claude — local study app.

Runs a small HTTP server on 127.0.0.1 that serves the study interface,
reads _app/data/program.json (generated by _build/make_index.py), keeps
progress in _app/data/progress.json, and opens slide decks and lecture
notes in whatever application the system already uses for them.

    python _app\\server.py

Nothing is sent anywhere. The server binds to the loopback address only.
"""
import io, os, re, sys, json, socket, threading, webbrowser
import http.server
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
STATIC = os.path.join(HERE, "static")
DATA = os.path.join(HERE, "data")
INDEX = os.path.join(DATA, "program.json")
PROGRESS = os.path.join(DATA, "progress.json")

# Only these may be opened through /api/open, and only from inside ROOT.
OPENABLE = (".pdf", ".pptx")

HOST = "127.0.0.1"
PORT = 8731


# --------------------------------------------------------------- progress
_lock = threading.Lock()


def read_progress():
    try:
        with io.open(PROGRESS, encoding="utf-8") as f:
            d = json.load(f)
    except (OSError, ValueError):
        d = {}
    d.setdefault("modules", {})   # "CSCE 679/9" -> "done" | "doing"
    d.setdefault("notes", {})     # same key -> free text
    return d


def write_progress(d):
    os.makedirs(DATA, exist_ok=True)
    tmp = PROGRESS + ".tmp"
    with io.open(tmp, "w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=1)
    os.replace(tmp, PROGRESS)


# ----------------------------------------------------------------- opening
def safe_target(relpath):
    """Resolve a repo-relative path, refusing anything outside ROOT."""
    if not relpath or ".." in relpath.replace("\\", "/").split("/"):
        return None
    full = os.path.normpath(os.path.join(ROOT, relpath.replace("/", os.sep)))
    if os.path.commonpath([os.path.realpath(full),
                           os.path.realpath(ROOT)]) != os.path.realpath(ROOT):
        return None
    if os.path.splitext(full)[1].lower() not in OPENABLE:
        return None
    if not os.path.isfile(full):
        return None
    return full


def open_file(full):
    if sys.platform.startswith("win"):
        os.startfile(full)                               # noqa: S606
    elif sys.platform == "darwin":
        os.system('open "%s"' % full)
    else:
        os.system('xdg-open "%s"' % full)


# ------------------------------------------------------------------ server
class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=STATIC, **kw)

    def log_message(self, fmt, *args):
        # args may contain non-strings (HTTPStatus, from log_error), so
        # stringify before testing. Only API traffic and errors are noted.
        line = " ".join(str(a) for a in args)
        if "/api/" in line or "code 4" in line or "code 5" in line:
            sys.stderr.write("  %s\n" % line)

    # ---- helpers
    def _json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _body(self):
        n = int(self.headers.get("Content-Length") or 0)
        if not n:
            return {}
        try:
            return json.loads(self.rfile.read(n).decode("utf-8"))
        except ValueError:
            return {}

    # ---- routes
    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path

        if path == "/api/program":
            try:
                with io.open(INDEX, encoding="utf-8") as f:
                    body = f.read().encode("utf-8")
            except OSError:
                return self._json(
                    {"error": "program.json missing. Run "
                              "_build/make_index.py first."}, 503)
            self.send_response(200)
            self.send_header("Content-Type",
                             "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            return self.wfile.write(body)

        if path == "/api/progress":
            with _lock:
                return self._json(read_progress())

        return super().do_GET()

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        data = self._body()

        if path == "/api/progress":
            key, state = data.get("key"), data.get("state")
            note = data.get("note")
            if not key:
                return self._json({"error": "key required"}, 400)
            with _lock:
                d = read_progress()
                if state in (None, "", "none"):
                    d["modules"].pop(key, None)
                elif state in ("doing", "done"):
                    d["modules"][key] = state
                else:
                    return self._json({"error": "bad state"}, 400)
                if note is not None:
                    if note.strip():
                        d["notes"][key] = note[:4000]
                    else:
                        d["notes"].pop(key, None)
                write_progress(d)
                return self._json(d)

        if path == "/api/open":
            full = safe_target(data.get("path", ""))
            if not full:
                return self._json({"error": "refused"}, 400)
            try:
                open_file(full)
            except OSError as e:
                return self._json({"error": str(e)}, 500)
            return self._json({"opened": os.path.basename(full)})

        if path == "/api/reindex":
            script = os.path.join(ROOT, "_build", "make_index.py")
            rc = os.system('"%s" "%s"' % (sys.executable, script))
            return self._json({"ok": rc == 0})

        return self._json({"error": "not found"}, 404)


def free_port(start):
    for p in range(start, start + 40):
        with socket.socket() as s:
            if s.connect_ex((HOST, p)) != 0:
                return p
    return start


def main():
    if not os.path.isfile(INDEX):
        print("No index yet. Running _build/make_index.py ...")
        os.system('"%s" "%s"'
                  % (sys.executable,
                     os.path.join(ROOT, "_build", "make_index.py")))

    port = free_port(PORT)
    httpd = http.server.ThreadingHTTPServer((HOST, port), Handler)
    url = "http://%s:%d/" % (HOST, port)
    print("University of Claude  ->  %s" % url)
    print("Loopback only; nothing leaves this machine.  Ctrl-C to stop.")
    try:
        webbrowser.open(url)
    except Exception:
        pass
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nstopped")


if __name__ == "__main__":
    main()
