# -*- coding: utf-8 -*-
"""Regenerate DEAD-LINKS.md from linkcheck.json and the current sources.

Every figure here is computed. The first version of this file was typed by
hand and its "repaired" count was wrong within a day, because a repaired URL
is not a flag you set -- it is simply a URL the sources no longer cite.

    python make_deadlinks.py
"""
import io, os, re, sys, json, glob, collections

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "content"))
from make_readme import PLAN, load

LC = os.path.join(HERE, "linkcheck.json")
OUT = os.path.join(HERE, "DEAD-LINKS.md")


def still_cited(url, src):
    """True if the sources still cite this URL bare, i.e. not wrapped in an
    archive.org snapshot. A snapshot URL *contains* the original, so a plain
    substring test under-counts -- that bug once reported 11 repairs for 24."""
    for m in re.finditer(re.escape(url), src):
        if "web.archive.org/web/" not in src[max(0, m.start() - 60):m.start()]:
            return True
    return False


def main():
    lc = json.load(io.open(LC, encoding="utf-8"))
    src = "".join(io.open(p, encoding="utf-8").read()
                  for p in glob.glob(os.path.join(HERE, "content", "*.py")))

    dead = [u for u, v in lc.items() if v.get("recheck") == "dead"]
    remaining = [u for u in dead if still_cited(u, src)]
    repaired = len(dead) - len(remaining)

    # Where each one is cited, from the live course data rather than the
    # recorded "where" field, so a moved citation is reported correctly.
    where = collections.defaultdict(list)
    for sem, pkg, code, title in PLAN:
        m = load(pkg)
        if m is None:
            continue
        for _n, url, _d in (m.COURSE.get("materials") or []):
            if url in lc and url in remaining:
                where[url].append((sem, code, "materials"))
        for mod in m.MODULES:
            for r in (mod.get("resources") or []):
                if r[1] in remaining:
                    where[r[1]].append((sem, code, "M%02d" % mod["n"]))

    rows = []
    for u in remaining:
        w = where.get(u) or [(99, "?", "?")]
        w.sort()
        rows.append((w[0][0], w[0][1], ", ".join(x[2] for x in w), u))
    rows.sort()

    o = io.StringIO()
    o.write("# Dead external links still needing a replacement\n\n")
    o.write("Generated by `make_deadlinks.py`. Do not edit by hand.\n\n")
    o.write("Confirmed 404 by two independent methods (python urllib with "
            "cookie and\nredirect handling, and curl following redirects "
            "with a browser user-agent).\n\n")
    o.write("- **%d** links confirmed dead in total.\n" % len(dead))
    o.write("- **%d** already repaired - an archive.org snapshot, or a "
            "corrected URL\n  where the original was simply wrong.\n" % repaired)
    o.write("- **%d** still cited and still dead, listed below.\n\n" % len(rows))
    if rows:
        o.write("| Semester | Course | Where | Dead URL |\n|---|---|---|---|\n")
        for sem, code, w, u in rows:
            o.write("| S%d | %s | %s | `%s` |\n" % (sem, code, w, u))
    else:
        o.write("Nothing left.\n")
    o.write("\n## Reading this\n\n")
    o.write("No module is left without readings: each carries three to six "
            "resources,\nand the worst case is one module down to two. "
            "`check_links.py` re-runs the\naudit; this file is regenerated "
            "from its output.\n\n")
    o.write("A 200 proves a URL resolves. It does not prove it points at the "
            "work cited --\nsome sites answer every path with a search page."
            " Check what you get.\n")

    io.open(OUT, "w", encoding="utf-8").write(o.getvalue())
    print(OUT)
    print("%d dead, %d repaired, %d remaining" % (len(dead), repaired, len(rows)))


if __name__ == "__main__":
    main()
